# Task 1 — Exploratory Data Analysis (EDA)
## Social Media, Dopamine and Productivity

In [45]:
import pandas as pd
path = r"C:\Users\mlacr\Downloads\social_media_dopamine_productivity.csv"
df = pd.read_csv(path, encoding='utf-8', low_memory=False)
df.head()

,participant_id,data_source,synthetic_flag,age,age_group,gender,race_ethnicity,nationality,country_of_residence,education_level,employment_status,occupation_category,relationship_status,avg_daily_sm_hours,years_on_social_media,primary_platform,secondary_platform,daily_check_frequency,first_check_of_day,late_night_scrolling,sm_during_work_study,sm_during_meals,notifications_always_on,scroll_without_purpose,doomscrolling_frequency,content_type_consumed,avg_daily_screen_time_hours,avg_sleep_hours,sleep_quality,exercise_frequency,avg_work_study_hours_per_day,dopamine_rush_feel_score,reward_seeking_behavior,fomo_score,comparison_to_others_score,validation_seeking_score,boredom_to_phone_reflex,inability_to_delay_gratification,attention_span_minutes,deep_work_duration_minutes,task_switching_frequency,difficulty_starting_tasks,difficulty_maintaining_focus,mind_wandering_during_work,productivity_self_rating,tasks_completed_per_day,work_quality_self_rating,creative_output_frequency,reading_duration_minutes_per_day,memory_recall_difficulty,learning_retention_difficulty,decision_fatigue_score,mental_fog_frequency,irritability_when_offline,anxiety_when_phone_unavailable,restlessness_score,mood_dependency_on_sm,withdrawal_attempt_count,longest_detox_days,detox_relapse_reason,severity_stage,productivity_decline_score,dopamine_dysregulation_index,digital_wellbeing_score,sm_addiction_risk_score,notes
0,P0001,synthetic_ai,1,16,13-17,Female,South Asian,Indian,India,High school,Student,Education,Single,7.5,4,Instagram,YouTube,Constantly,Within 5 mins of waking,Daily,Always,Always,Yes,Yes,Daily,Short video/Reels,11.0,5.5,Poor,Never,6.0,9,5,8,7,8,Yes,Yes,8,20,High,Yes,Yes,Yes,4,3,4,Low,10,Yes,Yes,8,Daily,Yes,9,8,Yes,9,2,3,Boredom,Critical,8.8,9.2,2.1,9.5
1,P0002,synthetic_ai,1,17,13-17,Male,East Asian,Chinese,China,High school,Student,Education,Single,8.0,5,TikTok,YouTube,Constantly,Within 5 mins of waking,Daily,Always,Always,Yes,Yes,Daily,Short video/Reels,12.0,5.0,Very poor,Never,5.5,10,5,9,8,9,Yes,Yes,7,15,High,Yes,Yes,Yes,3,2,3,Low,8,Yes,Yes,9,Daily,Yes,10,9,Yes,10,1,1,Curiosity,Critical,9.5,9.8,1.5,9.8
2,P0003,synthetic_ai,1,15,13-17,Female,Black/African,Nigerian,Nigeria,High school,Student,Education,Single,6.5,3,TikTok,Instagram,Every few hours,Within 30 mins,Daily,Often,Often,Yes,Yes,Daily,Short video/Reels,10.0,6.0,Poor,1-2x/week,6.5,8,4,7,7,7,Yes,Yes,10,25,High,Yes,Yes,Yes,4,4,4,Low,12,Yes,Yes,7,Daily,Yes,8,7,Yes,8,2,5,Boredom,Severe,8.0,8.5,2.8,9.0
3,P0004,synthetic_ai,1,19,18-22,Male,White/Caucasian,American,USA,High school,Student,Education,Single,6.0,6,YouTube,Reddit,Every few hours,Within 30 mins,Daily,Often,Sometimes,Yes,Yes,Daily,Gaming/Tech content,10.5,6.0,Poor,1-2x/week,5.0,8,4,7,6,6,Yes,Yes,12,25,High,Yes,Yes,Yes,4,3,4,Low,15,Yes,Yes,7,Daily,Yes,8,8,Yes,9,3,7,Boredom,Severe,7.8,8.2,2.9,8.8
4,P0005,synthetic_ai,1,18,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,Student,Education,Single,7.0,4,Instagram,TikTok,Constantly,Within 5 mins of waking,Daily,Always,Often,Yes,Yes,Daily,Short video/Reels,11.5,5.5,Poor,Never,6.0,9,5,8,8,8,Yes,Yes,8,18,High,Yes,Yes,Yes,3,3,3,Low,10,Yes,Yes,8,Daily,Yes,9,9,Yes,9,2,4,FOMO,Critical,9.0,9.3,2.0,9.6

In [2]:
# 2) Quick overview: info, shape
print(df.shape)
df.info()

(300, 66)
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 66 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   participant_id                    300 non-null    str
 1   data_source                       300 non-null    str
 2   synthetic_flag                    300 non-null    int64
 3   age                               300 non-null    int64
 4   age_group                         300 non-null    str
 5   gender                            300 non-null    str
 6   race_ethnicity                    300 non-null    str
 7   nationality                       300 non-null    str
 8   country_of_residence              300 non-null    str
 9   education_level                   300 non-null    str
 10  employment_status                 300 non-null    str
 11  occupation_category               300 non-null    str
 12  relationship_status               300 non-null    str
 13  avg_daily_sm_hours                300 non-null    float64
 14  years_on_social_media             300 non-null    int64
 15  primary_platform                  300 non-null    str
 16  secondary_platform                297 non-null    str
 17  daily_check_frequency             300 non-null    str
 18  first_check_of_day                300 non-null    str
 19  late_night_scrolling              300 non-null    str
 20  sm_during_work_study              300 non-null    str
 21  sm_during_meals                   300 non-null    str
 22  notifications_always_on           300 non-null    str
 23  scroll_without_purpose            300 non-null    str
 24  doomscrolling_frequency           300 non-null    str
 25  content_type_consumed             300 non-null    str
 26  avg_daily_screen_time_hours       300 non-null    float64
 27  avg_sleep_hours                   300 non-null    float64
 28  sleep_quality                     300 non-null    str
 29  exercise_frequency                300 non-null    str
 30  avg_work_study_hours_per_day      300 non-null    float64
 31  dopamine_rush_feel_score          300 non-null    int64
 32  reward_seeking_behavior           300 non-null    int64
 33  fomo_score                        300 non-null    int64
 34  comparison_to_others_score        300 non-null    int64
 35  validation_seeking_score          300 non-null    int64
 36  boredom_to_phone_reflex           300 non-null    str
 37  inability_to_delay_gratification  300 non-null    str
 38  attention_span_minutes            300 non-null    int64
 39  deep_work_duration_minutes        300 non-null    int64
 40  task_switching_frequency          300 non-null    str
 41  difficulty_starting_tasks         300 non-null    str
 42  difficulty_maintaining_focus      300 non-null    str
 43  mind_wandering_during_work        300 non-null    str
 44  productivity_self_rating          300 non-null    int64
 45  tasks_completed_per_day           300 non-null    int64
 46  work_quality_self_rating          300 non-null    int64
 47  creative_output_frequency         300 non-null    str
 48  reading_duration_minutes_per_day  300 non-null    int64
 49  memory_recall_difficulty          300 non-null    str
 50  learning_retention_difficulty     300 non-null    str
 51  decision_fatigue_score            300 non-null    int64
 52  mental_fog_frequency              300 non-null    str
 53  irritability_when_offline         300 non-null    str
 54  anxiety_when_phone_unavailable    300 non-null    int64
 55  restlessness_score                300 non-null    int64
 56  mood_dependency_on_sm             300 non-null    str
 57  withdrawal_attempt_count          300 non-null    int64
 58  longest_detox_days                300 non-null    int64
 59  detox_relapse_reason              300 non-null    int64
 60  severity_stage                    211 non-null    str
 61  productivity_decline_score        300 non-null    str
 62  dopamine_dysregulation_index      300 non-null    float64
 63  digital_wellbeing_score           300 non-null    float64
 64  sm_addiction_risk_score           300 non-null    float64
 65  notes                             300 non-null    float64
dtypes: float64(8), int64(20), str(38)
memory usage: 239.0 KB

In [34]:
# 3) Missing values and summary
missing = df.isna().sum().sort_values(ascending=False)
missing[missing>0]

# full descriptive table
pd.set_option('display.max_columns', None)
pd.set_option("display.max_rows", None)
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
age,300.0,NaN,NaN,NaN,36.31,15.175029,15.0,24.0,33.5,46.25,75.0
age_group,300,7,36-49,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,300,3,Female,148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education_level,300,3,Undergraduate,151,NaN,NaN,NaN,NaN,NaN,NaN,NaN
employment_status,300,7,Full-time employed,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_daily_sm_hours,300.0,NaN,NaN,NaN,4.03,2.034181,0.5,2.5,3.5,5.5,9.0
years_on_social_media,300.0,NaN,NaN,NaN,7.503333,2.690872,3.0,5.0,8.0,10.0,14.0
primary_platform,300,9,Instagram,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN
daily_check_frequency,300,5,2-3 times a day,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
late_night_scrolling,300,5,Sometimes,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sm_during_work_study,300,5,Sometimes,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
doomscrolling_frequency,300,5,Rarely,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_sleep_hours,300.0,NaN,NaN,NaN,7.325,1.033005,4.5,6.875,7.5,8.0,9.0
sleep_quality,300,5,Good,146,NaN,NaN,NaN,NaN,NaN,NaN,NaN
exercise_frequency,300,4,1-2x/week,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dopamine_rush_feel_score,300.0,NaN,NaN,NaN,4.92,2.490168,1.0,3.0,4.0,7.0,10.0
fomo_score,300.0,NaN,NaN,NaN,4.59,2.142553,1.0,3.0,4.0,6.0,10.0
validation_seeking_score,300.0,NaN,NaN,NaN,3.92,2.449544,1.0,2.0,3.0,5.0,10.0
boredom_to_phone_reflex,300,4,Yes,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
inability_to_delay_gratification,300,4,Rarely,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
attention_span_minutes,300.0,NaN,NaN,NaN,27.44,16.017541,5.0,15.0,24.0,38.0,65.0
deep_work_duration_minutes,300.0,NaN,NaN,NaN,66.203333,38.697549,10.0,35.0,60.0,95.25,150.0
productivity_self_rating,300.0,NaN,NaN,NaN,6.37,2.229275,2.0,5.0,6.0,9.0,10.0
creative_output_frequency,300,6,Good,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reading_duration_minutes_per_day,300.0,NaN,NaN,NaN,35.48,19.723751,5.0,20.0,35.0,55.0,72.0
learning_retention_difficulty,300,4,Rarely,133,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mood_dependency_on_sm,300,4,Rarely,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# 5) Inspect top values for object columns (samples)
for col in df.columns:
    print(f"--- {col} ({df[col].nunique()} unique) ---")
    print(df[col].value_counts(dropna=False).head(10).to_string())
    print()

--- age (61 unique) ---
age
25    12
21    10
20    10
22    10
27    10
19     9
26     9
16     8
17     8
18     8

--- age_group (7 unique) ---
age_group
36-49    74
28-35    53
18-22    50
23-27    43
50-59    35
60+      27
13-17    18

--- gender (3 unique) ---
gender
Female        148
Male          145
Non-binary      7

--- education_level (3 unique) ---
education_level
Undergraduate    151
Postgraduate     110
High school       39

--- employment_status (7 unique) ---
employment_status
Full-time employed    188
Student                72
Retired                27
Part-time employed      6
Job seeker              3
Self-employed           2
Freelancer              2

--- avg_daily_sm_hours (18 unique) ---
avg_daily_sm_hours
2.0    34
3.5    33
2.5    26
5.5    25
1.5    23
5.0    22
3.0    22
4.5    19
4.0    17
6.5    15

--- years_on_social_media (12 unique) ---
years_on_social_media
9     41
4     40
5     39
8     35
10    35
6     32
7     25
12    25
11    13
3     11

--- primary_platform (9 unique) ---
primary_platform
Instagram        95
Facebook         89
YouTube          50
LinkedIn         26
TikTok           21
WeChat           12
Twitter/X         5
Douyin/TikTok     1
Reddit            1

--- daily_check_frequency (5 unique) ---
daily_check_frequency
2-3 times a day    114
Every few hours    101
Constantly          47
Once a day          35
Once a week          3

--- late_night_scrolling (5 unique) ---
late_night_scrolling
Sometimes    86
Rarely       83
Daily        72
Often        30
Never        29

--- sm_during_work_study (5 unique) ---
sm_during_work_study
Sometimes    100
Rarely        68
Often         67
Always        37
Never         28

--- doomscrolling_frequency (5 unique) ---
doomscrolling_frequency
Rarely       86
Daily        69
Sometimes    62
Often        53
Never        30

--- avg_sleep_hours (10 unique) ---
avg_sleep_hours
8.0    68
7.5    62
7.0    43
8.5    37
5.5    23
6.5    22
6.0    20
9.0    15
5.0     7
4.5     3

--- sleep_quality (5 unique) ---
sleep_quality
Good         146
Fair          75
Poor          43
Very good     26
Very poor     10

--- exercise_frequency (4 unique) ---
exercise_frequency
1-2x/week    102
3-4x/week     79
Daily         71
Never         48

--- dopamine_rush_feel_score (10 unique) ---
dopamine_rush_feel_score
4     55
2     46
3     38
6     34
5     28
7     26
9     25
8     23
1     15
10    10

--- fomo_score (10 unique) ---
fomo_score
4     55
5     52
2     46
3     38
6     31
7     28
8     24
1     15
9      8
10     3

--- validation_seeking_score (10 unique) ---
validation_seeking_score
1     61
3     55
4     39
2     38
5     35
7     21
6     17
9     16
8     15
10     3

--- boredom_to_phone_reflex (4 unique) ---
boredom_to_phone_reflex
Yes          113
Sometimes     87
Rarely        72
Never         28

--- inability_to_delay_gratification (4 unique) ---
inability_to_delay_gratification
Rarely       109
Sometimes     80
Yes           72
Never         39

--- attention_span_minutes (30 unique) ---
attention_span_minutes
26    27
28    22
48    19
8     18
22    18
20    16
16    15
38    15
10    14
55    14

--- deep_work_duration_minutes (47 unique) ---
deep_work_duration_minutes
65     27
70     21
115    19
55     16
38     15
95     14
130    14
100    13
35     11
22     11

--- productivity_self_rating (9 unique) ---
productivity_self_rating
5     74
9     74
7     49
4     32
3     26
10    15
6     14
8     10
2      6

--- creative_output_frequency (6 unique) ---
creative_output_frequency
Good         116
Moderate      76
Low           57
Very good     30
Excellent     15
Very low       6

--- reading_duration_minutes_per_day (39 unique) ---
reading_duration_minutes_per_day
40    28
55    24
20    23
38    20
12    14
28    13
58    13
10    11
22    11
68    11

--- learning_retention_difficulty (4 unique) ---
learning_retention_difficulty
Rarely       133
Yes           91
Sometimes     49
Never         27

--- mood_dependency_on_sm (4 unique) ---
mood_dependency_on_sm
Rarely       102
Yes           73
Sometimes     66
Never         59

Due to the large number of variables in the dataset we are going to focus the EDA in the following selection:

- Concerning demographics: `age`, `age_group`, `gender`, `education_level` and `employment_status`.
- Concerning social media use: `avg_daily_sm_hours`, `years_on_social_media`, `primary_platform`, `daily_check_frequency`, `late_night_scrolling`, `sm_during_work_study`, `doomscrolling_frequency`.
- Concerning dopamine boosting and dependency related behaviour: `dopamine_rush_feel_score`, `fomo_score`, `validation_seeking_score`,`boredom_to_phone_reflex`, `inability_to_delay_gratification`, `mood_dependency_on_sm`.
- Concerning productivity: `attention_span_minutes`, `deep_work_duration_minutes`, `productivity_self_rating`, `creative_output_frequency`,`learning_retention_difficulty`, `reading_duration_minutes_per_day`.
- Other potentially relevant variables: `avg_sleep_hours`, `sleep_quality`,`exercise_frequency`.

The selected variables allow us to explore the relationship between social media use, dopamine-related behaviours, and productivity, while considering demographic and lifestyle factors that may be associated with these patterns.
This selection allows us to keep the EDA focused and manageable.

In [28]:
df=df.drop(columns=[col for col in df.columns if col not in ["age", "age_group", "gender", "education_level", "employment_status",
"avg_daily_sm_hours", "years_on_social_media", "primary_platform", "daily_check_frequency", "late_night_scrolling", 
"sm_during_work_study",  "doomscrolling_frequency",
"dopamine_rush_feel_score", "fomo_score", "validation_seeking_score","boredom_to_phone_reflex", "inability_to_delay_gratification", 
"mood_dependency_on_sm","attention_span_minutes", "deep_work_duration_minutes", "productivity_self_rating", 
 "creative_output_frequency","learning_retention_difficulty", "reading_duration_minutes_per_day","avg_sleep_hours", 
 "sleep_quality","exercise_frequency"
]],
          errors="ignore")

In [43]:
categorical = set(df.select_dtypes(include=["object", "str"]).columns)

units = {
    "age": "years",
    "avg_daily_sm_hours": "hours/day",
    "years_on_social_media": "years",
    "avg_daily_screen_time_hours": "hours/day",
    "avg_sleep_hours": "hours/night",
    "avg_work_study_hours_per_day": "hours/day",
    "dopamine_rush_feel_score": "1–10 score",
    "reward_seeking_behavior": "1–10 score",
    "fomo_score": "1–10 score",
    "validation_seeking_score": "1–10 score",
    "attention_span_minutes": "minutes",
    "deep_work_duration_minutes": "minutes",
    "productivity_self_rating": "1–10 score",
    "reading_duration_minutes_per_day": "minutes/day",
 
}

datatype ={
    "age": "Numerical discrete", 
    "age_group": "Categorical ordinal", 
    "gender": "Categorical nominal", 
    "education_level": "Categorical nominal", 
    "employment_status": "Categorical nominal",
    "avg_daily_sm_hours": "Numerical discrete",
    "years_on_social_media": "Numerical discrete",
    "primary_platform": "Categorical nominal",
    "daily_check_frequency": "Categorical ordinal",
    "late_night_scrolling": "Categorical ordinal",
    "sm_during_work_study": "Categorical ordinal",
    "doomscrolling_frequency": "Categorical ordinal",
    "dopamine_rush_feel_score": "Numerical discrete",
    "fomo_score": "Numerical discrete",
    "validation_seeking_score": "Numerical discrete",
    "boredom_to_phone_reflex": "Categorical ordinal",
    "inability_to_delay_gratification": "Categorical ordinal",
    "mood_dependency_on_sm": "Categorical ordinal",
    "attention_span_minutes": "Numerical discrete",
    "deep_work_duration_minutes": "Numerical discrete",
    "productivity_self_rating": "Numerical discrete",
    "creative_output_frequency": "Categorical nominal",
    "learning_retention_difficulty": "Categorical nominal",
    "reading_duration_minutes_per_day": "Numerical discrete",
    "avg_sleep_hours": "Numerical discrete",
    "sleep_quality": "Categorical ordinal",
    "exercise_frequency": "Categorical ordinal"

}



def temporal_geo(c):
    return "Geographic" if c in {"country_of_residence", "nationality"} else "No"

def domain(c):
    s = df[c]
    if c in categorical:
        n = s.dropna().nunique()
        if n <= 12:
            return ", ".join(map(str, sorted(s.dropna().unique())))
        return f"{n} distinct categories"
    return f"{s.min():g} to {s.max():g}"

metadata_rows = []
for c in df.columns:
    metadata_rows.append({
        "Field": c,
        "Data type": df[c].dtype.name,
        "Kind": datatype.get(c),
        "Temporal / geographic...": temporal_geo(c),
        "Domain / range": domain(c),
        "Unit / precision": units.get(c, "Category label" if c in categorical else "Numeric value; precision as stored"),
        "Missing": int(df[c].isna().sum()),
        "Unique": int(df[c].nunique(dropna=True)),
    })

field_dictionary = pd.DataFrame(metadata_rows)

In [44]:
from IPython.display import display, HTML

html_table = field_dictionary.to_html(
    index=False,
    classes="dataframe",
    escape=False
)

display(HTML(f"""
<div style="
    max-height: 500px;
    overflow: auto;
    border: 1px solid #ddd;
">
    {html_table}
</div>
"""))