# Task 1 — Exploratory Data Analysis (EDA)
## Social Media, Dopamine and Productivity

In [1]:
import pandas as pd
path = r"C:\Users\mlacr\Downloads\social_media_dopamine_productivity.csv"
df = pd.read_csv(path, encoding='utf-8', low_memory=False)
df.head()

,participant_id,data_source,synthetic_flag,age,age_group,gender,race_ethnicity,nationality,country_of_residence,education_level,...,mood_dependency_on_sm,withdrawal_attempt_count,longest_detox_days,detox_relapse_reason,severity_stage,productivity_decline_score,dopamine_dysregulation_index,digital_wellbeing_score,sm_addiction_risk_score,notes
0,P0001,synthetic_ai,1,16,13-17,Female,South Asian,Indian,India,High school,...,Yes,9,2,3,Boredom,Critical,8.8,9.2,2.1,9.5
1,P0002,synthetic_ai,1,17,13-17,Male,East Asian,Chinese,China,High school,...,Yes,10,1,1,Curiosity,Critical,9.5,9.8,1.5,9.8
2,P0003,synthetic_ai,1,15,13-17,Female,Black/African,Nigerian,Nigeria,High school,...,Yes,8,2,5,Boredom,Severe,8.0,8.5,2.8,9.0
3,P0004,synthetic_ai,1,19,18-22,Male,White/Caucasian,American,USA,High school,...,Yes,9,3,7,Boredom,Severe,7.8,8.2,2.9,8.8
4,P0005,synthetic_ai,1,18,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,...,Yes,9,2,4,FOMO,Critical,9.0,9.3,2.0,9.6

In [2]:
# 2) Quick overview: info, shape
print(df.shape)
df.info()

(300, 66)
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 66 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   participant_id                    300 non-null    str
 1   data_source                       300 non-null    str
 2   synthetic_flag                    300 non-null    int64
 3   age                               300 non-null    int64
 4   age_group                         300 non-null    str
 5   gender                            300 non-null    str
 6   race_ethnicity                    300 non-null    str
 7   nationality                       300 non-null    str
 8   country_of_residence              300 non-null    str
 9   education_level                   300 non-null    str
 10  employment_status                 300 non-null    str
 11  occupation_category               300 non-null    str
 12  relationship_status               300 non-null    str
 13  avg_daily_sm_hours                300 non-null    float64
 14  years_on_social_media             300 non-null    int64
 15  primary_platform                  300 non-null    str
 16  secondary_platform                297 non-null    str
 17  daily_check_frequency             300 non-null    str
 18  first_check_of_day                300 non-null    str
 19  late_night_scrolling              300 non-null    str
 20  sm_during_work_study              300 non-null    str
 21  sm_during_meals                   300 non-null    str
 22  notifications_always_on           300 non-null    str
 23  scroll_without_purpose            300 non-null    str
 24  doomscrolling_frequency           300 non-null    str
 25  content_type_consumed             300 non-null    str
 26  avg_daily_screen_time_hours       300 non-null    float64
 27  avg_sleep_hours                   300 non-null    float64
 28  sleep_quality                     300 non-null    str
 29  exercise_frequency                300 non-null    str
 30  avg_work_study_hours_per_day      300 non-null    float64
 31  dopamine_rush_feel_score          300 non-null    int64
 32  reward_seeking_behavior           300 non-null    int64
 33  fomo_score                        300 non-null    int64
 34  comparison_to_others_score        300 non-null    int64
 35  validation_seeking_score          300 non-null    int64
 36  boredom_to_phone_reflex           300 non-null    str
 37  inability_to_delay_gratification  300 non-null    str
 38  attention_span_minutes            300 non-null    int64
 39  deep_work_duration_minutes        300 non-null    int64
 40  task_switching_frequency          300 non-null    str
 41  difficulty_starting_tasks         300 non-null    str
 42  difficulty_maintaining_focus      300 non-null    str
 43  mind_wandering_during_work        300 non-null    str
 44  productivity_self_rating          300 non-null    int64
 45  tasks_completed_per_day           300 non-null    int64
 46  work_quality_self_rating          300 non-null    int64
 47  creative_output_frequency         300 non-null    str
 48  reading_duration_minutes_per_day  300 non-null    int64
 49  memory_recall_difficulty          300 non-null    str
 50  learning_retention_difficulty     300 non-null    str
 51  decision_fatigue_score            300 non-null    int64
 52  mental_fog_frequency              300 non-null    str
 53  irritability_when_offline         300 non-null    str
 54  anxiety_when_phone_unavailable    300 non-null    int64
 55  restlessness_score                300 non-null    int64
 56  mood_dependency_on_sm             300 non-null    str
 57  withdrawal_attempt_count          300 non-null    int64
 58  longest_detox_days                300 non-null    int64
 59  detox_relapse_reason              300 non-null    int64
 60  severity_stage                    211 non-null    str
 61  productivity_decline_score        300 non-null    str
 62  dopamine_dysregulation_index      300 non-null    float64
 63  digital_wellbeing_score           300 non-null    float64
 64  sm_addiction_risk_score           300 non-null    float64
 65  notes                             300 non-null    float64
dtypes: float64(8), int64(20), str(38)
memory usage: 239.0 KB

In [3]:
# 3) Missing values and summary
missing = df.isna().sum().sort_values(ascending=False)
missing[missing>0]

# full descriptive table
pd.set_option('display.max_columns', None)
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
participant_id,300,300,P0001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_source,300,1,synthetic_ai,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
synthetic_flag,300.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
age,300.0,NaN,NaN,NaN,36.31,15.175029,15.0,24.0,33.5,46.25,75.0
age_group,300,7,36-49,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
productivity_decline_score,300,5,None/Minimal,154,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dopamine_dysregulation_index,300.0,NaN,NaN,NaN,4.354333,2.750095,0.5,1.8,3.2,6.2,9.9
digital_wellbeing_score,300.0,NaN,NaN,NaN,4.853667,2.692319,1.0,2.4,3.8,6.8,10.0
sm_addiction_risk_score,300.0,NaN,NaN,NaN,6.170333,2.649709,1.1,4.2,7.0,8.8,9.9
notes,300.0,NaN,NaN,NaN,5.006,2.922093,0.5,2.2,4.0,7.2,10.0

In [4]:
# 5) Inspect top values for object columns (samples)
for col in df.select_dtypes(include=['object']).columns:
    print(f"--- {col} ({df[col].nunique()} unique) ---")
    print(df[col].value_counts(dropna=False).head(10).to_string())
    print()

--- participant_id (300 unique) ---
participant_id
P0001    1
P0002    1
P0003    1
P0004    1
P0005    1
P0006    1
P0007    1
P0008    1
P0009    1
P0010    1

--- data_source (1 unique) ---
data_source
synthetic_ai    300

--- age_group (7 unique) ---
age_group
36-49    74
28-35    53
18-22    50
23-27    43
50-59    35
60+      27
13-17    18

--- gender (3 unique) ---
gender
Female        148
Male          145
Non-binary      7

--- race_ethnicity (7 unique) ---
race_ethnicity
White/Caucasian    72
East Asian         63
Black/African      54
South Asian        52
Hispanic/Latino    43
Middle Eastern     15
Native American     1

--- nationality (39 unique) ---
nationality
Indian          26
American        24
Nigerian        15
Chinese         14
Mexican         12
Pakistani       12
British         12
Australian      12
South Korean    12
Japanese        10

--- country_of_residence (39 unique) ---
country_of_residence
India          26
USA            24
Nigeria        15
China          14
Mexico         12
Pakistan       12
UK             12
Australia      12
South Korea    12
Japan          10

--- education_level (3 unique) ---
education_level
Undergraduate    151
Postgraduate     110
High school       39

--- employment_status (7 unique) ---
employment_status
Full-time employed    188
Student                72
Retired                27
Part-time employed      6
Job seeker              3
Self-employed           2
Freelancer              2

--- occupation_category (14 unique) ---
occupation_category
Education     96
Technology    32
Other         30
Healthcare    27
Finance       23
Government    19
Retail        13
Creative      12
Business      12
Research      12

--- relationship_status (4 unique) ---
relationship_status
Married              153
Single               109
In a relationship     34
Divorced               4

--- primary_platform (9 unique) ---
primary_platform
Instagram        95
Facebook         89
YouTube          50
LinkedIn         26
TikTok           21
WeChat           12
Twitter/X         5
Douyin/TikTok     1
Reddit            1

--- secondary_platform (16 unique) ---
secondary_platform
YouTube          65
TikTok           55
Instagram        47
LinkedIn         37
Facebook         31
Twitter/X        18
WhatsApp         18
Reddit           12
Douyin/TikTok     3
Telegram          3

--- daily_check_frequency (5 unique) ---
daily_check_frequency
2-3 times a day    114
Every few hours    101
Constantly          47
Once a day          35
Once a week          3

--- first_check_of_day (4 unique) ---
first_check_of_day
Within 30 mins             150
Within 1 hour               87
Within 5 mins of waking     48
During morning routine      15

--- late_night_scrolling (5 unique) ---
late_night_scrolling
Sometimes    86
Rarely       83
Daily        72
Often        30
Never        29

--- sm_during_work_study (5 unique) ---
sm_during_work_study
Sometimes    100
Rarely        68
Often         67
Always        37
Never         28

--- sm_during_meals (5 unique) ---
sm_during_meals
Rarely       110
Sometimes     91
Often         44
Never         39
Always        16

--- notifications_always_on (2 unique) ---
notifications_always_on
Yes    205
No      95

--- scroll_without_purpose (4 unique) ---
scroll_without_purpose
Rarely       108
Yes          104
Sometimes     48
Never         40

--- doomscrolling_frequency (5 unique) ---
doomscrolling_frequency
Rarely       86
Daily        69
Sometimes    62
Often        53
Never        30

--- content_type_consumed (76 unique) ---
content_type_consumed
Short video/Reels        33
Tech/Professional        20
Lifestyle/Fashion        15
Gaming/Tech content      12
Family/Religious         11
News/Professional         9
Educational/Parenting     9
Health/Parenting          8
Health/Professional       8
Educational/Social        7

--- sleep_quality (5 unique) ---
sleep_quality
Good         146
Fair          75
Poor          43
Very good     26
Very poor     10

--- exercise_frequency (4 unique) ---
exercise_frequency
1-2x/week    102
3-4x/week     79
Daily         71
Never         48

--- boredom_to_phone_reflex (4 unique) ---
boredom_to_phone_reflex
Yes          113
Sometimes     87
Rarely        72
Never         28

--- inability_to_delay_gratification (4 unique) ---
inability_to_delay_gratification
Rarely       109
Sometimes     80
Yes           72
Never         39

--- task_switching_frequency (3 unique) ---
task_switching_frequency
Low         160
Moderate     75
High         65

--- difficulty_starting_tasks (4 unique) ---
difficulty_starting_tasks
Rarely       121
Sometimes     77
Yes           75
Never         27

--- difficulty_maintaining_focus (4 unique) ---
difficulty_maintaining_focus
Sometimes    106
Rarely        92
Yes           87
Never         15

--- mind_wandering_during_work (4 unique) ---
mind_wandering_during_work
Rarely       131
Sometimes     68
Yes           62
Never         39

--- creative_output_frequency (6 unique) ---
creative_output_frequency
Good         116
Moderate      76
Low           57
Very good     30
Excellent     15
Very low       6

--- memory_recall_difficulty (4 unique) ---
memory_recall_difficulty
Rarely       133
Yes          128
Sometimes     24
Never         15

--- learning_retention_difficulty (4 unique) ---
learning_retention_difficulty
Rarely       133
Yes           91
Sometimes     49
Never         27

--- mental_fog_frequency (5 unique) ---
mental_fog_frequency
Never        85
Rarely       76
Daily        65
Often        55
Sometimes    19

--- irritability_when_offline (4 unique) ---
irritability_when_offline
Rarely       108
Yes           91
Sometimes     61
Never         40

--- mood_dependency_on_sm (4 unique) ---
mood_dependency_on_sm
Rarely       102
Yes           73
Sometimes     66
Never         59

--- severity_stage (14 unique) ---
severity_stage
Boredom               126
NaN                    89
Comparison             27
FOMO                   26
Validation seeking     15
Low motivation          4
Perfectionism           3
Overwhelm               3
Curiosity               1
Peer pressure           1

--- productivity_decline_score (5 unique) ---
productivity_decline_score
None/Minimal    154
Early            53
Critical         35
Severe           29
Moderate         29

C:\Users\mlacr\AppData\Local\Temp\ipykernel_54132\1469388838.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

In [9]:
categorical = set(df.select_dtypes(include=["object", "str"]).columns)

units = {
    "age": "years",
    "avg_daily_sm_hours": "hours/day",
    "years_on_social_media": "years",
    "avg_daily_screen_time_hours": "hours/day",
    "avg_sleep_hours": "hours/night",
    "avg_work_study_hours_per_day": "hours/day",
    "dopamine_rush_feel_score": "1–10 score",
    "reward_seeking_behavior": "1–10 score",
    "fomo_score": "1–10 score",
    "comparison_to_others_score": "1–10 score",
    "validation_seeking_score": "1–10 score",
    "attention_span_minutes": "minutes",
    "deep_work_duration_minutes": "minutes",
    "productivity_self_rating": "1–10 score",
    "tasks_completed_per_day": "tasks/day",
    "work_quality_self_rating": "1–10 score",
    "reading_duration_minutes_per_day": "minutes/day",
    "decision_fatigue_score": "1–10 score",
    "anxiety_when_phone_unavailable": "1–10 score",
    "restlessness_score": "1–10 score",
    "withdrawal_attempt_count": "attempts",
    "longest_detox_days": "days",
    "detox_relapse_reason": "coded numeric score; unit undocumented",
    "dopamine_dysregulation_index": "composite index (0–10)",
    "digital_wellbeing_score": "composite index (0–10)",
    "sm_addiction_risk_score": "composite index (0–10)",
    "notes": "numeric value; unit undocumented",
}

special_desc = {
    "participant_id": "Unique participant identifier; nominal identifier.",
    "data_source": "Source label for the records.",
    "synthetic_flag": "Binary flag indicating whether the data are synthetic.",
    "age": "Participant age.",
    "age_group": "Age band derived from age.",
    "gender": "Self-reported gender category.",
    "race_ethnicity": "Race/ethnicity category.",
    "nationality": "Nationality category; overlaps strongly with country_of_residence.",
    "country_of_residence": "Country where the participant resides; geographic categorical field.",
    "education_level": "Education category.",
    "employment_status": "Employment status category.",
    "occupation_category": "Broad occupation category.",
    "relationship_status": "Relationship status category.",
    "primary_platform": "Main social-media platform.",
    "secondary_platform": "Secondary social-media platform, if any.",
    "productivity_decline_score": "Ordinal outcome describing reported productivity decline.",
}

def field_description(c):
    return special_desc.get(
        c,
        "Categorical behavioral/self-report variable." if c in categorical
        else "Numeric behavioral, psychological or productivity measure."
    )

def temporal_geo(c):
    return "Geographic" if c in {"country_of_residence", "nationality"} else "No temporal dimension"

def domain(c):
    s = df[c]
    if c in categorical:
        n = s.dropna().nunique()
        if n <= 12:
            return ", ".join(map(str, sorted(s.dropna().unique())))
        return f"{n} distinct categories"
    return f"{s.min():g} to {s.max():g}"

metadata_rows = []
for c in df.columns:
    metadata_rows.append({
        "Field": c,
        "Data type": str(df[c].dtype),
        "Kind": "Categorical" if c in categorical else "Numerical",
        "Temporal / geographic": temporal_geo(c),
        "Domain / range": domain(c),
        "Unit / precision": units.get(c, "Category label" if c in categorical else "Numeric value; precision as stored"),
        "Missing": int(df[c].isna().sum()),
        "Unique": int(df[c].nunique(dropna=True)),
        "Description": field_description(c),
    })

field_dictionary = pd.DataFrame(metadata_rows)

In [10]:
from IPython.display import display, HTML

html_table = field_dictionary.to_html(
    index=False,
    classes="dataframe",
    escape=False
)

display(HTML(f"""
<div style="
    max-height: 500px;
    overflow: auto;
    border: 1px solid #ddd;
">
    {html_table}
</div>
"""))